### ISSUE TITLE
Date doesn't work (wrong format in unit test)

### ISSUE THREAD

**Issue by tfonfara** [tenaciousRas/android-plist-parser#6]
Hi,

the date format in the unit test is wrong (have a look at http://www.apple.com/DTDs/PropertyList-1.0.dtd):

``` java
public static final String VALID_PLIST_DATE_ROOT = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>"
            + "<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">"
            + "<plist version=\"1.0\">"
            + "<date>"
            + "Sun, 13 Feb 2011 12:01:00 GMT-0500" + "</date>" + "</plist>";
```

The correct date format in plist files is [ISO 8601](http://en.wikipedia.org/wiki/ISO_8601) ("Contents should conform to a subset of ISO 8601 [in particular, YYYY '-' MM '-' DD 'T' HH ':' MM ':' SS 'Z'"]) e.g. 2012-02-24T10:10:00Z but this format throws an exception during parsing.

Can you help please?

Thank you!

**Comment by tenaciousRas** [comment]
Sounds fine.  The existing test case should stay and a new one added for the proper ISO format b/c the existing test expresses real-world usage.

Date#setValue(java.lang.String val) line 63 needs to be updated for ISO 8601 format support.

**Comment by tfonfara** [comment]
Suggestion for Date#setValue(java.lang.String val):

``` java
@Override
public void setValue(java.lang.String val) {
    try {
        this.date = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss").parse(val);
    } catch (ParseException e) {
        this.date = new java.util.Date(java.util.Date.parse(val.trim()));
        //e.printStackTrace();
    }
}
```

**Comment by tenaciousRas** [comment]
should be fixed

**Comment by tfonfara** [comment]
thanks, it works fine!
